### ISSUE TITLE
能否更新一下代码，改用stable编译

### ISSUE THREAD

**Issue by golovo** [zjp-CN/rustdx#31]
如果不是nightly版本，还编译不了。。。

**Comment by zjp-CN** [comment]
很简单的，移除 `#![feature(doc_auto_cfg)]` 就好了，应该没怎么用到 nightly 功能。

**Comment by golovo** [comment]
> 很简单的，移除 `#![feature(doc_auto_cfg)]` 就好了，应该没怎么用到 nightly 功能。

嗯，我下载源代码学习时，这么干了。但是我想用cargo add rustdx调用您的包就没法改了

**Comment by zjp-CN** [comment]
好的，有空我会更新一个版本，移除这个。你暂时先用 path 的方式引入依赖吧。

**Comment by golovo** [comment]
> 好的，有空我会更新一个版本，移除这个。你暂时先用 path 的方式引入依赖吧。

太感谢了！

**Comment by zjp-CN** [comment]
在 https://github.com/zjp-CN/rustdx/tree/v0.4.1 已完成，新版本也发布了

**Comment by golovo** [comment]
> 在 https://github.com/zjp-CN/rustdx/tree/v0.4.1 已完成，新版本也发布了

谢谢！
